# Generated by Django 4.2.13 on 2024-06-09 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='ArtistName',
            new_name='Artist_Name',
        ),
    ]
